version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 30
      runas: centos
    - location: scripts/start_server
      timeout: 30
      runas: centos
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 30
      runas: centos

